name = "cf-image-hosting"
pages_build_output_dir = "./dist"
compatibility_date = "2024-04-30"

# 🌍 统一归入生产环境配置
[env.production]
# 这里的变量原本在 .vars 下面，我们可以直接合并或者写在 env.production 作用域下
vars = { API_HOST = "https://telegra.ph" }

# 📥 将图片 KV 严格绑定在生产环境下
[[env.production.kv_namespaces]]
binding = "img_kv"
id = "b23bea2b559e4367bd7ee7fac5574622"

# 🔒 将认证 KV 严格绑定在生产环境下
[[env.production.kv_namespaces]]
binding = "auth_kv"
id = "a27aa2f6a2ef42a8bfe3373e57530661"
